export const ImageList = [
  {
    id: 1,
    image: "https://picsum.photos/200/300",
    imageDetails: "1",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",
    addWatermark: true,
    includeEXIF: true,
    camera: "X-T30 II",
    lens: "XC15-45mmF3.5-5.6 OIS PZ",
    focalLength: 26.4,
    shutterSpeed: "1/102",
    aperture: 5.6,
    iso: 125,
    shootDate: "2023-07-21",
  },
  {
    id: 2,
    image: "https://picsum.photos/200/300",
    imageDetails: "2",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",
    addWatermark: true,
    includeEXIF: true,
    camera: "Canon EOS R5",
    lens: "RF24-105mm F4 L IS USM",
    focalLength: 50,
    shutterSpeed: "1/200",
    aperture: 4.0,
    iso: 400,
    shootDate: "2023-06-15",
  },
  {
    id: 3,
    image: "https://picsum.photos/200/300",
    imageDetails: "3",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",
    addWatermark: true,
    includeEXIF: true,
    camera: "Nikon D850",
    lens: "AF-S NIKKOR 24-70mm f/2.8E ED VR",
    focalLength: 35,
    shutterSpeed: "1/60",
    aperture: 2.8,
    iso: 800,
    shootDate: "2023-05-10",
  },
  {
    id: 4,
    image: "https://picsum.photos/200/300",
    imageDetails: "4",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",
    addWatermark: true,
    includeEXIF: true,
    camera: "Sony A7 III",
    lens: "FE 24-70mm F2.8 GM",
    focalLength: 24,
    shutterSpeed: "1/125",
    aperture: 2.8,
    iso: 200,
    shootDate: "2023-04-20",
  },
  {
    id: 5,
    image: "https://picsum.photos/200/300",
    imageDetails: "5",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",
    addWatermark: true,
    includeEXIF: true,
    camera: "Olympus OM-D E-M1 Mark III",
    lens: "M.Zuiko Digital ED 12-40mm F2.8 PRO",
    focalLength: 40,
    shutterSpeed: "1/80",
    aperture: 2.8,
    iso: 1600,
    shootDate: "2023-03-25",
  },
  {
    id: 6,
    image: "https://picsum.photos/200/300",
    imageDetails: "6",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",
    addWatermark: true,
    includeEXIF: true,
    camera: "Panasonic Lumix GH5",
    lens: "Leica DG Vario-Elmarit 12-60mm F2.8-4.0 ASPH",
    focalLength: 60,
    shutterSpeed: "1/250",
    aperture: 4.0,
    iso: 3200,
    shootDate: "2023-02-18",
  },
  {
    id: 7,
    image: "https://picsum.photos/200/300",
    imageDetails: "7",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "",
    addWatermark: true,
    includeEXIF: true,
    camera: "Fujifilm X-T4",
    lens: "XF16-55mm F2.8 R LM WR",
    focalLength: 55,
    shutterSpeed: "1/500",
    aperture: 2.8,
    iso: 6400,
    shootDate: "2023-01-30",
  },
  {
    id: 8,
    image: "https://picsum.photos/200/300",
    imageDetails: "8",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "",
    addWatermark: true,
    includeEXIF: true,
    camera: "Leica Q2",
    lens: "Summilux 28mm f/1.7 ASPH",
    focalLength: 28,
    shutterSpeed: "1/1000",
    aperture: 1.7,
    iso: 100,
    shootDate: "2023-01-01",
  },
];
