export const ImageList = [
  {
    id: 1,
    image: "https://picsum.photos/200/300",
    imageDetails: "1",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 2,
    image: "https://picsum.photos/200/300",
    imageDetails: "2",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 3,
    image: "https://picsum.photos/200/300",
    imageDetails: "3",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "private",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 4,
    image: "https://picsum.photos/200/300",
    imageDetails: "4",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 5,
    image: "https://picsum.photos/200/300",
    imageDetails: "5",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 6,
    image: "https://picsum.photos/200/300",
    imageDetails: "6",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "link",

    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 7,
    image: "https://picsum.photos/200/300",
    imageDetails: "7",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "",
    addWatermark: true,
    includeEXIF: true,
  },
  {
    id: 8,
    image: "https://picsum.photos/200/300",
    imageDetails: "8",
    additionalDetails: "",
    type: "",
    tag: [],
    location: "",
    private: "",

    addWatermark: true,
    includeEXIF: true,
  },
];
