export const Profile = [
  {
    username: "LAMARR GOLDING",
    location: "London, United Kingdom",
    profilePicture: "https://example.com/path/to/profile-picture1.jpg",
    coverPhoto: "https://example.com/path/to/cover-photo1.jpg",
    followers: 6890,
    following: 96,
    photoLikes: 23400,
    photoImpressions: 1700000,
    contactEmail: "lamarr.golding2@gmail.com",
    bio: "A visual journal of my Adventures. Contact: Lamarr.golding2@gmail.com",
    tabs: [
      {
        name: "Photos",
        count: 271,
        images: [
          { url: "https://example.com/photos/photo1.jpg" },
          { url: "https://example.com/photos/photo2.jpg" },
          { url: "https://example.com/photos/photo3.jpg" },
          { url: "https://example.com/photos/photo4.jpg" },
          { url: "https://example.com/photos/photo5.jpg" },
          { url: "https://example.com/photos/photo6.jpg" },
          { url: "https://example.com/photos/photo7.jpg" },
          { url: "https://example.com/photos/photo8.jpg" },
          { url: "https://example.com/photos/photo9.jpg" },
          { url: "https://example.com/photos/photo10.jpg" },
        ],
      },
      {
        name: "Galleries",
        count: 7,
        images: [
          { url: "https://example.com/galleries/gallery1.jpg" },
          { url: "https://example.com/galleries/gallery2.jpg" },
          { url: "https://example.com/galleries/gallery3.jpg" },
          { url: "https://example.com/galleries/gallery4.jpg" },
          { url: "https://example.com/galleries/gallery5.jpg" },
          { url: "https://example.com/galleries/gallery6.jpg" },
          { url: "https://example.com/galleries/gallery7.jpg" },
          { url: "https://example.com/galleries/gallery8.jpg" },
          { url: "https://example.com/galleries/gallery9.jpg" },
          { url: "https://example.com/galleries/gallery10.jpg" },
        ],
      },
      {
        name: "Licensing",
        count: 64,
        images: [
          { url: "https://example.com/licensing/license1.jpg" },
          { url: "https://example.com/licensing/license2.jpg" },
          { url: "https://example.com/licensing/license3.jpg" },
          { url: "https://example.com/licensing/license4.jpg" },
          { url: "https://example.com/licensing/license5.jpg" },
          { url: "https://example.com/licensing/license6.jpg" },
          { url: "https://example.com/licensing/license7.jpg" },
          { url: "https://example.com/licensing/license8.jpg" },
          { url: "https://example.com/licensing/license9.jpg" },
          { url: "https://example.com/licensing/license10.jpg" },
        ],
      },
    ],
    socialLinks: {
      instagram: "https://instagram.com/lamarrgolding",
      website: "https://lamarrgolding.com",
    },
  },
  {
    username: "JANE DOE",
    location: "New York, USA",
    profilePicture: "https://example.com/path/to/profile-picture2.jpg",
    coverPhoto: "https://example.com/path/to/cover-photo2.jpg",
    followers: 12000,
    following: 150,
    photoLikes: 45000,
    photoImpressions: 2500000,
    contactEmail: "jane.doe@example.com",
    bio: "Photographer and traveler. Contact: jane.doe@example.com",
    tabs: [
      {
        name: "Photos",
        count: 300,
        images: [
          { url: "https://example.com/photos/photo11.jpg" },
          { url: "https://example.com/photos/photo12.jpg" },
          { url: "https://example.com/photos/photo13.jpg" },
          { url: "https://example.com/photos/photo14.jpg" },
          { url: "https://example.com/photos/photo15.jpg" },
          { url: "https://example.com/photos/photo16.jpg" },
          { url: "https://example.com/photos/photo17.jpg" },
          { url: "https://example.com/photos/photo18.jpg" },
          { url: "https://example.com/photos/photo19.jpg" },
          { url: "https://example.com/photos/photo20.jpg" },
        ],
      },
      {
        name: "Galleries",
        count: 10,
        images: [
          { url: "https://example.com/galleries/gallery11.jpg" },
          { url: "https://example.com/galleries/gallery12.jpg" },
          { url: "https://example.com/galleries/gallery13.jpg" },
          { url: "https://example.com/galleries/gallery14.jpg" },
          { url: "https://example.com/galleries/gallery15.jpg" },
          { url: "https://example.com/galleries/gallery16.jpg" },
          { url: "https://example.com/galleries/gallery17.jpg" },
          { url: "https://example.com/galleries/gallery18.jpg" },
          { url: "https://example.com/galleries/gallery19.jpg" },
          { url: "https://example.com/galleries/gallery20.jpg" },
        ],
      },
      {
        name: "Licensing",
        count: 80,
        images: [
          { url: "https://example.com/licensing/license11.jpg" },
          { url: "https://example.com/licensing/license12.jpg" },
          { url: "https://example.com/licensing/license13.jpg" },
          { url: "https://example.com/licensing/license14.jpg" },
          { url: "https://example.com/licensing/license15.jpg" },
          { url: "https://example.com/licensing/license16.jpg" },
          { url: "https://example.com/licensing/license17.jpg" },
          { url: "https://example.com/licensing/license18.jpg" },
          { url: "https://example.com/licensing/license19.jpg" },
          { url: "https://example.com/licensing/license20.jpg" },
        ],
      },
    ],
    socialLinks: {
      instagram: "https://instagram.com/janedoe",
      website: "https://janedoe.com",
    },
  },
  {
    username: "JOHN SMITH",
    location: "Sydney, Australia",
    profilePicture: "https://example.com/path/to/profile-picture3.jpg",
    coverPhoto: "https://example.com/path/to/cover-photo3.jpg",
    followers: 5000,
    following: 200,
    photoLikes: 15000,
    photoImpressions: 1000000,
    contactEmail: "john.smith@example.com",
    bio: "Nature enthusiast and photographer. Contact: john.smith@example.com",
    tabs: [
      {
        name: "Photos",
        count: 150,
        images: [
          { url: "https://example.com/photos/photo21.jpg" },
          { url: "https://example.com/photos/photo22.jpg" },
          { url: "https://example.com/photos/photo23.jpg" },
          { url: "https://example.com/photos/photo24.jpg" },
          { url: "https://example.com/photos/photo25.jpg" },
          { url: "https://example.com/photos/photo26.jpg" },
          { url: "https://example.com/photos/photo27.jpg" },
          { url: "https://example.com/photos/photo28.jpg" },
          { url: "https://example.com/photos/photo29.jpg" },
          { url: "https://example.com/photos/photo30.jpg" },
        ],
      },
      {
        name: "Galleries",
        count: 5,
        images: [
          { url: "https://example.com/galleries/gallery21.jpg" },
          { url: "https://example.com/galleries/gallery22.jpg" },
          { url: "https://example.com/galleries/gallery23.jpg" },
          { url: "https://example.com/galleries/gallery24.jpg" },
          { url: "https://example.com/galleries/gallery25.jpg" },
          { url: "https://example.com/galleries/gallery26.jpg" },
          { url: "https://example.com/galleries/gallery27.jpg" },
          { url: "https://example.com/galleries/gallery28.jpg" },
          { url: "https://example.com/galleries/gallery29.jpg" },
          { url: "https://example.com/galleries/gallery30.jpg" },
        ],
      },
      {
        name: "Licensing",
        count: 50,
        images: [
          { url: "https://example.com/licensing/license21.jpg" },
          { url: "https://example.com/licensing/license22.jpg" },
          { url: "https://example.com/licensing/license23.jpg" },
          { url: "https://example.com/licensing/license24.jpg" },
          { url: "https://example.com/licensing/license25.jpg" },
          { url: "https://example.com/licensing/license26.jpg" },
          { url: "https://example.com/licensing/license27.jpg" },
          { url: "https://example.com/licensing/license28.jpg" },
          { url: "https://example.com/licensing/license29.jpg" },
          { url: "https://example.com/licensing/license30.jpg" },
        ],
      },
    ],
    socialLinks: {
      instagram: "https://instagram.com/johnsmith",
      website: "https://johnsmith.com",
    },
  },
];
