name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script:
          cd /home/deploy/pure-pixel-frontend
          git checkout main
          git pull
          yarn install
          yarn build
