# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH - VPS to deploy
      uses: appleboy/ssh-action@master
      with:
        node-version: ${{ matrix.node-version }}
        clean: false
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/home/deploy/pure-pixel-frontend
          git checkout main
          git pull
          yarn
          yarn build
